twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_4_layout.html.twig"]
  globals:
    paths:
      "%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates": KnpPaginator

when@test:
  twig:
    strict_variables: true
